version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    container_name: cerveza-cristal-dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - PORT=3000
    volumes:
      - .:/app
      - /app/node_modules
      - /app/build
    command: npm run dev
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3" 